### ISSUE TITLE
v0.2 has missing dependencies.

### ISSUE THREAD

**Issue by Ahmed-Hindy** [AgastyaPatel/USD_Megascan_Importer#2]
as the title says, it appears the shelf tools are missing some dependencies. which results in empty icons on shelf, gives errors, and the 'open AssetManager tool' crashes Houdini when it opens the python panels.

I would suggest installing using packages with a $PATH 
which includes subfolders like 'scripts' and 'toolbar'.
this will make installation easier for user.

**Comment by AgastyaPatel** [comment]
I think I know why this is happening...

Add this in the .env file in Houdini's pref folder
`HOUDINI_SCRIPT_PATH = C:\Users\<username>\Documents\houdini20.0\scripts`
Replace `username` as in your system

**Comment by AgastyaPatel** [comment]
Kindly Reopen this thread if issue persist.
